---
title: "Warm Up 6"
author: "Frankie Lin"
date: "3/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

#loading Packages
```{r}
library(knitr)
library(dplyr)
library(tidyverse)
```

#1) Future Value Function
```{r}
#' @title future_value
#' @description calculates the future value of a compounded interest function
#' @param amount initial invested amount
#' @param rate annual rate of return
#' @param years number of years
#' @return calculated future value

future_value <- function(amount, rate, years){
  amount * (1 + rate)^years
}

future_value(amount = 100, rate = 0.05, years = 1)
future_value(amount = 500, rate = 0.05, years = 5)
future_value(amount = 1000, rate = 0.05, years = 10)
```

#2) Future Value Annuity
```{r}
#' @title annuity
#' @description calculates the future value of an annuity compounded yearly
#' @param contrib contribution (i.e. how much you deposit at the end of each year)
#' @param rate annual rate of return
#' @param years number of years
#' @return calculated value of future annuity

annuity <- function(contrib, rate, years){
  contrib * ((((1 + rate)^years) - 1)/rate)
}

annuity(contrib = 200, rate = 0.05, years = 1)
annuity(contrib = 200, rate = 0.05, years = 2)
annuity(contrib = 200, rate = 0.05, years = 10)
```

#3) Future Value of Growing Annuity
```{r}
#' @title growing_annuity
#' @description calculates the future value of a growing annuity compounded yearly
#' @param contrib contribution (i.e. how much you deposit at the end of each year)
#' @param growth growth rate
#' @param rate annual rate of return
#' @param years number of years
#' @return calculated value of a growing annuity

growing_annuity <- function(contrib, growth, rate, years){
  contrib * ((1 + rate)^years - (1 + growth)^years)/(rate - growth) 
}

growing_annuity(contrib = 200, rate = 0.05, growth = 0.03, years = 1)
growing_annuity(contrib = 200, rate = 0.05, growth = 0.03, years = 2)
growing_annuity(contrib = 200, rate = 0.05, growth = 0.03, years = 10)

```

#4) Investing Modalities
```{r}
# mode 1
future_value(1000, rate = 0.05, years = 10)

# mode 2
future_value(1000, rate = 0.05, years = 10) + annuity(contrib = 200, rate = 0.05, years = 10)

# mode 3
future_value(1000, rate = 0.05, years = 10) + growing_annuity(contrib = 200, rate = 0.05, growth = 0.03, years = 10)
```

##4.1) For-loop and Table
```{r}
# time vector
times <- 0:10

#defining each of the column vectors
mode_1 <- c()
mode_2 <- c()
mode_3 <- c()

#for loop to fill out data table
for (i in 1:length(times)){
  # mode 1 calc
  mode_1[i] <- future_value(1000, rate = 0.05, years = times[i])
  
  # mode 2 calc
  mode_2[i] <- future_value(1000, rate = 0.05, years = times[i]) + annuity(contrib = 200, rate = 0.05, years = times[i])
  
  # mode 3 calc
  mode_3[i] <- future_value(1000, rate = 0.05, years = times[i]) + growing_annuity(contrib = 200, rate = 0.05, growth = 0.03, years = times[i])
}
  
#creating modalities dataframe
modalities <- data.frame(year = times, no_contrib = mode_1, fixed_contrib = mode_2, growing_contrib = mode_3)
kable(modalities)
```

##4.2) Plot
```{r}
plot(x = modalities$year, y = modalities$growing_contrib, 
     type = "l",
     col = "#1C7CF0",
     xlab = "Time (in Years)", 
     ylab = "Return (in Dollars)", 
     main = "!0 year Return Rates of Different Investing Modalities")
lines(x = modalities$year,  y = modalities$fixed_contrib, col = "#DA3D1A")
lines(x = modalities$year,  y = modalities$no_contrib, col = "#3BBE18")
legend("topleft", c("Mode 1", "Mode 2", "Mode 3"), lty = c(1, 1, 1), col = c("#3BBE18",  "#DA3D1A","#1C7CF0"))
```

#5) Savings Simulation
## 5.1) Data Generating Process
```{r}
# intitial data vectors
time_period <- 0:15
rates <- c(0.001, 0.0225, 0.065)
modes <- c("no_contrib", "fixed_contrib", "growing_contrib")

# expand grad data points
combos <- expand.grid(rates, modes, time_period)
names(combos) <- c("rates", "modes", "time_period")

#output vector
balance <- numeric(nrow(combos))

#simple for loop
for (row_index in 1:nrow(combos)){
  if (combos[row_index, "modes"] == "no_contrib"){
    balance[row_index] = future_value(10000, rate = combos[row_index, "rates"], years = combos[row_index, "time_period"])
  } else if (combos[row_index, "modes"] == "fixed_contrib") {
    balance[row_index] = future_value(10000, rate = combos[row_index, "rates"],
                 years = combos[row_index, "time_period"]) + annuity(contrib = 2000, rate = combos[row_index, "rates"], years = combos[row_index, "time_period"])
  } else {
    balance[row_index] = future_value(10000, rate = combos[row_index, "rates"], years = combos[row_index, "time_period"]) + growing_annuity(contrib = 2000, rate = combos[row_index, "rates"], growth = 0.04, years = combos[row_index, "time_period"])
  }
}

#merging data frame
balance.df <- cbind(combos, balance)

#fixing columns
balance.df$rates <- factor(balance.df$rates)

#adding names
names <- c(`0.001` = "Regular Savings",
          `0.0225` = "High Yield Savings",
          `0.065` = "Index Fund"
            )
```

## 5.2) Return on Investment plot
```{r}
ggplot(balance.df, aes(x = time_period, y = balance, col = factor(modes))) +
  geom_point() + 
  geom_line() + 
  facet_grid(~rates, labeller = as_labeller(names)) + 
  scale_color_discrete(name = "Modality") +
  xlab("Time Period") + 
  ylab("Balance") + 
  ggtitle("Investment Returns")
```




