---
title: "Lab 9"
author: "Frankie Lin"
date: "4/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

#Loading Packages
```{r}
# load testthat
library(testthat)
```

# Part 1) Practice Writing Simple Tests
```{r}
test_file("tests.R")
```

# Part 2) Basics of String Manipulation*
```{r}
# Laoding US Arrests Dataframe
data(USArrests)
names(USArrests)

# States Names Vector
states <- rownames(USArrests)

```

## Your Turn*: paste()
```{r}
paste(head(states), nchar(head(states)), sep = " = ")
```

## Your Turn*: Permutations
```{r}
factorial(nchar("Alabama"))
```

## Your turn*: Converting Temperatures
```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  switch(tolower(to),
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

## Your Turn*: Names of files
```{r}
# vector of file names
## way 1
(filenames <- paste0("file", 1:10, ".csv"))

##way 2
(filenames <- paste("file", 1:10, ".csv", sep = ""))

##way 3 
filenames <- numeric(10)
for (i in 1:10) {
  filenames[i] <- paste0("file", i, ".csv")
}
filenames

# rename vector of file names
gsub("file", "dataset", filenames)
```

#Your turn*: cat()
```{r}
# name of output file
outfile <- "output.txt"

# writing to 'outfile.txt'
cat("---", file = outfile)
cat("\ntitle: 'Some title'", file = outfile, append = TRUE)
cat("\nauthor: 'Your name'", file = outfile, append = TRUE)
cat("\ndate: 'today's date'", file = outfile, append = TRUE)
cat("\noutput: html_document", file = outfile, append = TRUE)
cat("\n---", file = outfile, append = TRUE)

cat("\n\n", file = outfile, append = TRUE)
cat("This is the first line", file = outfile, append = TRUE)
cat("\nA 2nd line", file = outfile, append = TRUE)

cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)
```

#Your Turn*: Valid Color Names
```{r}
is_color <- function(col){
  if (tolower(col) %in% colors()){
    return(TRUE)
  }
  return(FALSE)
}

is_color('yellow')  # TRUE

is_color('blu')     # FALSE

is_color('turkuoise') # FALSE
```

# Plot with a valid color
```{r}
colplot <- function(input_color){
  if (is_color(input_color)){
    return(plot(runif(10, 0, 1), runif(10, 0, 1), col = tolower(input_color)))
  }
  stop(paste("invalid color", input_color))
}

# this should plot
colplot('tomato')

# this stops with error message
colplot('tomate')
```






